### ISSUE TITLE
Run-Bakery download returns a 404.

### ISSUE THREAD

**Issue by hnelson** [silitics/rugix#46]
When trying to upgrade from .7 to .8, I encountered the following error when trying to upgrade run-bakery:
```
hnelson@Hughs-MacBook-Pro rugix % curl -O https://raw.githubusercontent.com/silitics/rugix/v0.8/bakery/run-bakery && chmod +x ./run-bakery
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    14  100    14    0     0     73      0 --:--:-- --:--:-- --:--:--    74
hnelson@Hughs-MacBook-Pro rugix % cat run-bakery                                                                                          
404: Not Found%
```

Thanks!

**Comment by hnelson** [comment]
I found I can download the run-bakery script by chasing the URL to `https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/bakery/run-bakery`, however I run into a further error when the `rugix-bakery` script attempts to pull down the latest Docker image.
```
hnelson@Hughs-MacBook-Pro rugix % ./run-bakery bake image tryboot-pi4                                                                    
v0.8: Pulling from silitics/rugix-bakery
Digest: sha256:120a379fd997e4bf65074cebfe4317ce857f322b431e7385a10b8662c52fabc5
Status: Image is up to date for ghcr.io/silitics/rugix-bakery:v0.8
ghcr.io/silitics/rugix-bakery:v0.8
Error: unable to find image tryboot-pi4
╰╴at crates/tools/rugix-bakery/src/oven/mod.rs:32:24
```

**Comment by reubenmiller** [comment]
Also there are json schemas available that you can add to most Rugix tomls files. For example for the `rugix-bakery.toml`, you can add the following `#:schema` header to the file.

```toml
#:schema https://raw.githubusercontent.com/silitics/rugix/refs/tags/v0.8.0/schemas/rugix-bakery-project.schema.json

[repositories]
rugix-extra = { git = "https://github.com/silitics/rugix-extra.git", branch = "v0.8" }

# rest of your config
```

Then if you're using a modern IDE, then you should get some validation and auto completion help (though in some IDEs you might need to install an extension for toml)
